### ISSUE TITLE
Disable including individual mods?

### ISSUE THREAD

**Issue by carpenteer** [MSchmoecker/HammerTime#1]
There should be a way to disable including a mod's "hammer" into this mod's functionality.

Right now this mod absorbs the various runes from the Rune Focus from the Rune Magic mod, but those "pieces" require the runic energy from the focus to "cast" and thus don't work (in that they show 0 resources to "build" with) when combined into the vanilla hammer.

**Comment by MSchmoecker** [comment]
Thanks for the suggestion. I added a config option to disable moving pieces from individual hammers in version 0.1.1. Also Rune Magic is automatically disabled.
