### ISSUE TITLE
Not recognizing PotteryBarn by ComfyMods

### ISSUE THREAD

**Issue by lightsourced** [MSchmoecker/HammerTime#10]
The new update is amazing, really love being able to add modded items to vanilla categories!! I did notice however that it's not letting me edit the location for PotteryBarn by ComfyMods: https://valheim.thunderstore.io/package/ComfyMods/PotteryBarn/

**Comment by MSchmoecker** [comment]
Thanks, the bug was already noticed and we are discussing it with the PotteryBarn author https://github.com/redseiko/ComfyMods/issues/20. I think the incompatibility should be fixed inside PotteryBarn and thus I will wait a bit before attempting to solve it here.

**Comment by MSchmoecker** [comment]
Fixed in the PotteryBarn mod and should now work
