### ISSUE TITLE
Not Hiding Construction by MrSerji build hammer

### ISSUE THREAD

**Issue by lightsourced** [MSchmoecker/HammerTime#12]
I have hide hammer selected in the config and all the other hammers are hidden except for this one: https://valheim.thunderstore.io/package/MrSerji/Construction/0.2.5/

**Comment by MSchmoecker** [comment]
This works fine on my setup when only HammerTime and Construction are installed. The recipe gets disabled if 'Disable Hammer Recipes' is turned on and is no longer visible at the workbench. Maybe you have another mod that turns it back on? Also note that this option will not remove already crafted hammers, only disable the recipes for them.

**Comment by lightsourced** [comment]
I figured it out, it's because there was a config option in his own mod that would enable/disable the hammer and I had it enabled! Woopsie!
