### ISSUE TITLE
Not separating out into specified sections

### ISSUE THREAD

**Issue by lightsourced** [MSchmoecker/HammerTime#13]
I have several mods where I am configuring them to default to vanilla categories, however, their original categories remain but are empty. 

https://imgur.com/a/5vDD72Y

I'm using the new ComfyMods build panel redesign that is a replacement for ComfyBuildExpansion, SearsCatalog (https://valheim.thunderstore.io/package/ComfyMods/SearsCatalog/1.0.0/).

**Comment by lightsourced** [comment]
Can I get you any other information for this issue? I'm happy to help in any way! It's so cumbersome having so many tabs with nothing in them :(

**Comment by MSchmoecker** [comment]
What mods are you using where their original categories remain? I see "VikingLibrary" in your screenshot but cannot find any mod by this name.

**Comment by lightsourced** [comment]
Sure!

https://valheim.thunderstore.io/package/JiuJitsu/Constructed_Kingdoms_Secret_Bookcases/1.0.1/
https://valheim.thunderstore.io/package/OdinPlus/OdinArchitect/1.1.1/
https://valheim.thunderstore.io/package/ComfyMods/PotteryBarn/1.4.0/
https://valheim.thunderstore.io/package/RagnarokHCRP/MoreGates/

**Comment by MSchmoecker** [comment]
Alright, after a bit of digging I found the issue. PlanBuild is adding categories for all pieces as well on a different tool, which wasn't distinguished by HammerTime and thought that the category must be enabled.

That's easy to fix, will release a fix with version 0.3.3
