### ISSUE TITLE
Hammertime incompatible with Auga build menu

### ISSUE THREAD

**Issue by Karmacopper** [MSchmoecker/HammerTime#14]
I'm getting the following with the latest version of Auga:
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Jotunn.Managers.PieceManager.CreateCategoryTabs () (at D:/Projects/Jotunn/JotunnLib/Managers/PieceManager.cs:604)
Jotunn.Managers.PieceManager.AddPieceCategory (System.String table, System.String name) (at D:/Projects/Jotunn/JotunnLib/Managers/PieceManager.cs:311)
HammerTime.Plugin.MovePieceItemToTable (HammerTime.PieceItem pieceItem, System.String pieceTableFrom, System.String pieceTableTo, System.String category) (at <274a1be5124d4a139a450a965c797d5a>:0)
HammerTime.Plugin.UpdatePieceTables () (at <274a1be5124d4a139a450a965c797d5a>:0)
HammerTime.Plugin.IndexPrefabs () (at <274a1be5124d4a139a450a965c797d5a>:0)
HammerTime.Patches+ObjectDBPatch.ObjectDBAwake () (at <274a1be5124d4a139a450a965c797d5a>:0)
(wrapper dynamic-method) DungeonDB.DMD<DungeonDB::Start>(DungeonDB)

Valheim  0.214.300 (23/5/2023)
BebipEx 5.4.2102
Hammertime 0.3.3
Auga 1.2.5

**Comment by MSchmoecker** [comment]
Fixed in HammerTime 0.3.4, Jotunn 2.11.4 and Auga 1.2.8
