### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by EnergyBridge** [MSchmoecker/HammerTime#18]
![HammerTime Log Error](https://github.com/user-attachments/assets/a797b9bc-0704-4209-940a-81c0edc0aae7)

Hello there, hope you are doing well! 

I have a strange issue. I am running HammerTIme, BuildPiecesCustomized, and many other mods (everything is built from Thunderstore with R2Modman, including those with custom build hammers). I ran into a weird issue where the Clutter mod by Plumga on Thunderstore (among others) will no longer be added as a category and not show up in the HammerTime config file when it did before. (Clutter will show up in the HammerTime config if I make a new mod profile with R2modman so I know Clutter still works with HammerTime). In the log, it says there is an error:

[Warning: HammerTime.Config] Config 'Enable Hammer' for _ClutterPieceTable not found

It does this for another mod called PlantIt as well. Oddly, it started after I was editing bpcsave files from the BuildPiecesCustomized mod (was messing with the category number for a couple build pieces). I also noticed that the issue started right when I removed two building piece mods as well (removing their categories from the vanilla hammer - those mods were RavenwoodDwarvenKingdoms by JamesJonesTV, and RavenwoodPieces by JamesJonesTV). 

Is there any way I can fix this? I already tried to delete the HammerTime config file while the game was not running (one file called "com.maxsch.valheim.HammerTime.cfg"), run the game again, and look at the new config file and Clutter and others are still not in the HammerTIme config list. I also tried uninstalling the entire mod, and reinstalling it, and it is not detecting several mods like Clutter anymore. Has no issue finding it on another new mod profile though.

[errors.txt](https://github.com/user-attachments/files/17070296/errors.txt)

I uploaded a photo of one of the errors, as well as an Errors log (there are several "index" errors that all started right when HammerTime started losing access to mods in it's config file.)

Huge thank you for the help if you have time! Trying to save the mod profile.

**Comment by MSchmoecker** [comment]
Please send the full log. Also the HammerTime warnings aren't inside the file you send.

However, whatever mod is causing the first PieceTable error, is likely the reason for the issue. Unfortunately, it's hard to tell which mod is causing it.
