### ISSUE TITLE
Please filter Rune Magic Rune out

### ISSUE THREAD

**Issue by 4Magma** [MSchmoecker/HammerTime#2]
https://www.nexusmods.com/valheim/mods/1359 (name: runeFocus)

or if possible make tools and Categories editable
- for each compatible tool create config section, with
  - Enabled/Disabled (default off)
  - name field for each category

**Comment by 4Magma** [comment]
Sorry, had forgotten to check for closed issues.

**Comment by MSchmoecker** [comment]
Since 0.1.1, Rune Magic is already disabled by default.

The names are dynamically created with at least 4 tabs + 1 combined tab. I don't really want to put this inside a config, as this are too many names without much gain for renaming the tabs.
