### ISSUE TITLE
Integration with Project Auga

### ISSUE THREAD

**Issue by ustropics** [MSchmoecker/HammerTime#3]
First off, amazing work and great mod. Any chance you can integrate this with Project Auga? The build menu is not contained to the Project Auga window (the categories extend outside of it). In my image below you can see what I mean ("crafting" is not within the drawn window of Auga).

![image](https://user-images.githubusercontent.com/49380013/167244049-574ae833-c59f-4895-bf93-9340e87938d3.png)

**Comment by MSchmoecker** [comment]
This is a bug in Auga and has to be fixed there. To be presize, it is an incompatibility between Auga an Jotunn, because Jotunn is managing the custom tabs.

Maybe I do a small patch sometime, as I am not optimistic Auga will fix it. But Auga bugs aren't high on my priority list.

**Comment by MSchmoecker** [comment]
Alright, I have fixed the tabs in the latest update (0.1.3)
