### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by lightsourced** [MSchmoecker/HammerTime#7]
I am wondering if it would be possible to add a config option to where you can disable the recipe for the added tools from appearing in your workbench. Would be so nice to make it less cluttered!

**Comment by MSchmoecker** [comment]
Yes, this does sound good. I was already asked to disable the items, but this could mean unintentional item loss when trying the mod which isn't that nice.

But only disabling the recipe isn't destructive so this would be a nice quality of live update. When I have the time I will get to it.

**Comment by lightsourced** [comment]
I am trying out the updated mod with this added feature, I have "Disable Hammer Recipes" enabled, however, the shovel from plantit (https://valheim.thunderstore.io/package/OdinPlus/PlantIt/) still appears as a crafting recipe at the workbench.

It is recognizing the mod, because it has added it to the build menu and I have it set to combine hammer categories and that is all working as intended.
